include:
  - compose_files/docker-compose.postgres.yml
  - compose_files/docker-compose.backend.yml
  - compose_files/docker-compose.dagster.yml
  - compose_files/docker-compose.messaging.yml
  - compose_files/docker-compose.testing.yml
  - compose_files/docker-compose.nginx.yml
  - compose_files/docker-compose.plugin_integration.yml
  - compose_files/docker-compose.rdkit_plugin.yml
  - compose_files/docker-compose.tei_plugin.yml
  - compose_files/docker-compose.qdrant.yml
  # - compose_files/docker-compose.triton.yml
  - compose_files/docker-compose.mapper.yml 

networks:
  vvs_v2_network:
    driver: bridge
    name: vvs_v2_network

