plugins:
  qdrant_plugin:
    enabled: False
    profile: qdrant_plugin 
    requires_integration: True
  tei_plugin:
    enabled: False
    profile: tei_plugin 
    requires_integration: True
  rdkit_plugin:
    enabled: False
    profile: rdkit_plugin 
    requires_integration: False
  triton_plugin:
    enabled: True
    profile: triton_plugin
    requires_integration: False # TODO ADD INTEGRATION
  mapper_plugin:
    enabled: False
    profile: mapper_plugin
    requires_integration: True 

