services:
  backend:
    service_name: backend
    unit_test: False 
    integration_test: True 
  qdrant_plugin:
    service_name: qdrant_plugin
    unit_test: False # no unit tests
    integration_test: False 
  tei_plugin:
    service_name: tei_plugin
    unit_test: False # no unit tests
    integration_test: True 
  rdkit_plugin:
    service_name: rdkit_plugin
    unit_test: True 
    integration_test: False 
  triton_plugin:
    service_name: triton_plugin
    unit_test: False # no unit test
    integration_test: True 
  # mapper_plugin:
  #   service_name: mapper_plugin
  #   unit_test: False # no unit tests 
  #   integration_test: True 
temp_services:
  test_consumer:
    service_name: test_consumer
    profile: test_consumer
    enabled: True
  test_server:
    service_name: test_server
    profile: test_server
    enabled: True
