services:
  backend:
    build:
      context: ../  # Changed from ../backend to include both backend and database
      dockerfile: backend/backend.Dockerfile  # Updated path to the Dockerfile
    env_file:
      - ../.env
    entrypoint:
      - fastapi
      - run 
      - "app/main.py"
      - --port 
      - "${BACKEND_PORT}"
      - --host
      - "${BACKEND_HOST}"
      - --workers
      - "${BACKEND_WORKERS}"
    expose:
      - ${BACKEND_PORT}
    networks:
      - vvs_v2_network
    depends_on:
      - postgresql
      - dagster_code_server
    deploy:
      replicas: ${BACKEND_REPLICAS:-${DEFAULT_REPLICAS}}

# services:
#   backend:
#     build:
#       context: ../backend
#       dockerfile: backend.Dockerfile 
#     env_file:
#       - ../.env
#     entrypoint:
#       - fastapi
#       - run 
#       - "app/main.py"
#       - --port 
#       - "${BACKEND_PORT}"
#       - --host
#       - "${BACKEND_HOST}"
#       - --workers
#       - "${BACKEND_WORKERS}"
#     expose:
#       - ${BACKEND_PORT}
#     networks:
#       - vvs_v2_network
#     depends_on:
#       - postgresql
#       - dagster_code_server
#     deploy:
#       replicas: ${BACKEND_REPLICAS:-${DEFAULT_REPLICAS}}