
services:
  qdrant:
    image: qdrant/qdrant:v1.11.4
    profiles: [plugin, qdrant_plugin]
    container_name: qdrant
    env_file:
      - ../.env
    networks:
      - vvs_v2_network
    expose:
      - ${QDRANT__SERVICE__HTTP_PORT}
      - ${QDRANT__SERVICE__GRPC_PORT}
    ports:
      - ${QDRANT__SERVICE__HTTP_PORT}:${QDRANT__SERVICE__HTTP_PORT}
      - ${QDRANT__SERVICE__GRPC_PORT}:${QDRANT__SERVICE__GRPC_PORT}
    volumes:
      - ${QDRANT_STORAGE_DIR}:/qdrant/storage
      - ${QDRANT_SNAPSHOT_DIR}:/qdrant/qdrant_snapshots
