services:
  postgresql:
    image: postgres:11
    container_name: postgresql
    env_file: 
      - ../.env 
    networks:
      - vvs_v2_network
    volumes:
       - ${POSTGRES_STORAGE}:/var/lib/postgresql/data
    # ports:
    #   - ${PGPORT}:${PGPORT}
