services:
  plugin_integration_server:
    build:
      context: ../plugin_integration_server
      dockerfile: plugin_integration_server.Dockerfile 
    profiles: [plugin, plugin_integration_server]
    env_file:
      - ../.env
    entrypoint:
      - fastapi
      - run 
      - "app/main.py"
      - --port 
      - "${PLUGIN_INTEGRATION_SERVER_PORT}"
      - --host
      - "${PLUGIN_INTEGRATION_SERVER_HOST}"
      - --workers
      - "${PLUGIN_INTEGRATION_SERVER_WORKERS}"
    # expose:
      # - ${PLUGIN_INTEGRATION_SERVER_PORT}
    ports:
      - ${PLUGIN_INTEGRATION_SERVER_PORT}:${PLUGIN_INTEGRATION_SERVER_PORT}
    networks:
      - vvs_v2_network
    deploy:
      replicas: ${PLUGIN_INTEGRATION_SERVER_REPLICAS:-${DEFAULT_REPLICAS}}

