services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    env_file:
      - ../.env
    expose:
      - "5672"
      - "15672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
    networks:
      - vvs_v2_network

  redis:
    image: redis:7-alpine
    container_name: redis
    env_file: ../.env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: >
          --requirepass ${REDIS_PASSWORD}
    networks:
      - vvs_v2_network

  message_consumer:
    build:
      context: ../message_consumer 
      dockerfile: message_consumer.Dockerfile 
    env_file:
      - ../.env
    networks:
      - vvs_v2_network
    depends_on:
      - rabbitmq
    deploy:
      replicas: ${MESSAGE_CONSUMER_REPLICAS:-${DEFAULT_REPLICAS}}

  dlx_consumer:
    build:
      context: ../message_consumer 
      dockerfile: dlx_consumer.Dockerfile 
    env_file:
      - ../.env
    networks:
      - vvs_v2_network
    depends_on:
      - rabbitmq
    deploy:
      replicas: ${DLX_CONSUMER_REPLICAS:-${DEFAULT_REPLICAS}}
  
